# Generated by Django 5.2.5 on 2025-08-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
