# Generated by Django 5.2.5 on 2025-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customermodel_email_alter_customermodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
