# Generated by Django 5.2.5 on 2025-08-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_tempmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
